; Auto-generated. Do not edit!


(cl:in-package visual_servoing-msg)


;//! \htmlinclude Tag_poseResult.msg.html

(cl:defclass <Tag_poseResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass Tag_poseResult (<Tag_poseResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Tag_poseResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Tag_poseResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name visual_servoing-msg:<Tag_poseResult> is deprecated: use visual_servoing-msg:Tag_poseResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Tag_poseResult>) ostream)
  "Serializes a message object of type '<Tag_poseResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Tag_poseResult>) istream)
  "Deserializes a message object of type '<Tag_poseResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Tag_poseResult>)))
  "Returns string type for a message object of type '<Tag_poseResult>"
  "visual_servoing/Tag_poseResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Tag_poseResult)))
  "Returns string type for a message object of type 'Tag_poseResult"
  "visual_servoing/Tag_poseResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Tag_poseResult>)))
  "Returns md5sum for a message object of type '<Tag_poseResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Tag_poseResult)))
  "Returns md5sum for a message object of type 'Tag_poseResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Tag_poseResult>)))
  "Returns full string definition for message of type '<Tag_poseResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Tag_poseResult)))
  "Returns full string definition for message of type 'Tag_poseResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Tag_poseResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Tag_poseResult>))
  "Converts a ROS message object to a list"
  (cl:list 'Tag_poseResult
))
