; Auto-generated. Do not edit!


(cl:in-package visual_servoing-msg)


;//! \htmlinclude Tag_poseGoal.msg.html

(cl:defclass <Tag_poseGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass Tag_poseGoal (<Tag_poseGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Tag_poseGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Tag_poseGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name visual_servoing-msg:<Tag_poseGoal> is deprecated: use visual_servoing-msg:Tag_poseGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Tag_poseGoal>) ostream)
  "Serializes a message object of type '<Tag_poseGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Tag_poseGoal>) istream)
  "Deserializes a message object of type '<Tag_poseGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Tag_poseGoal>)))
  "Returns string type for a message object of type '<Tag_poseGoal>"
  "visual_servoing/Tag_poseGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Tag_poseGoal)))
  "Returns string type for a message object of type 'Tag_poseGoal"
  "visual_servoing/Tag_poseGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Tag_poseGoal>)))
  "Returns md5sum for a message object of type '<Tag_poseGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Tag_poseGoal)))
  "Returns md5sum for a message object of type 'Tag_poseGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Tag_poseGoal>)))
  "Returns full string definition for message of type '<Tag_poseGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Tag_poseGoal)))
  "Returns full string definition for message of type 'Tag_poseGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Tag_poseGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Tag_poseGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'Tag_poseGoal
))
