/* Auto-generated by genmsg_cpp for file /home/jara/electric_workspace/ardrone_msgs/msg/Priority.msg */
#ifndef ARDRONE_MSGS_MESSAGE_PRIORITY_H
#define ARDRONE_MSGS_MESSAGE_PRIORITY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace ardrone_msgs
{
template <class ContainerAllocator>
struct Priority_ {
  typedef Priority_<ContainerAllocator> Type;

  Priority_()
  : priority(false)
  {
  }

  Priority_(const ContainerAllocator& _alloc)
  : priority(false)
  {
  }

  typedef uint8_t _priority_type;
  uint8_t priority;


private:
  static const char* __s_getDataType_() { return "ardrone_msgs/Priority"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "ccd365fab5966953d747f1c995f86413"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool priority\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, priority);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, priority);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(priority);
    return size;
  }

  typedef boost::shared_ptr< ::ardrone_msgs::Priority_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardrone_msgs::Priority_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Priority
typedef  ::ardrone_msgs::Priority_<std::allocator<void> > Priority;

typedef boost::shared_ptr< ::ardrone_msgs::Priority> PriorityPtr;
typedef boost::shared_ptr< ::ardrone_msgs::Priority const> PriorityConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ardrone_msgs::Priority_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ardrone_msgs::Priority_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ardrone_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ardrone_msgs::Priority_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ardrone_msgs::Priority_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ardrone_msgs::Priority_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ccd365fab5966953d747f1c995f86413";
  }

  static const char* value(const  ::ardrone_msgs::Priority_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xccd365fab5966953ULL;
  static const uint64_t static_value2 = 0xd747f1c995f86413ULL;
};

template<class ContainerAllocator>
struct DataType< ::ardrone_msgs::Priority_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ardrone_msgs/Priority";
  }

  static const char* value(const  ::ardrone_msgs::Priority_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ardrone_msgs::Priority_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool priority\n\
\n\
";
  }

  static const char* value(const  ::ardrone_msgs::Priority_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ardrone_msgs::Priority_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ardrone_msgs::Priority_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.priority);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Priority_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ardrone_msgs::Priority_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ardrone_msgs::Priority_<ContainerAllocator> & v) 
  {
    s << indent << "priority: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.priority);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ARDRONE_MSGS_MESSAGE_PRIORITY_H

